import type { Level } from "../ZipTypes";

export const LEVELS_HARD2: Level[] = [
  {
    id: 26,
    gridSize: 9,
    nodes: [
      { number: 1, position: { x: 0, y: 0 } },
      { number: 2, position: { x: 3, y: 0 } },
      { number: 3, position: { x: 6, y: 0 } },
      { number: 4, position: { x: 8, y: 3 } },
      { number: 5, position: { x: 8, y: 6 } },
      { number: 6, position: { x: 6, y: 8 } },
      { number: 7, position: { x: 3, y: 8 } },
      { number: 8, position: { x: 0, y: 8 } },
      { number: 9, position: { x: 4, y: 4 } },
    ],
    obstacles: [
      { x: 1, y: 1 },
      { x: 2, y: 2 },
      { x: 4, y: 1 },
      { x: 5, y: 2 },
      { x: 6, y: 3 },
      { x: 7, y: 5 },
      { x: 6, y: 6 },
      { x: 5, y: 7 },
      { x: 4, y: 6 },
      { x: 3, y: 5 },
      { x: 2, y: 5 },
      { x: 1, y: 4 },
      { x: 2, y: 3 },
      { x: 3, y: 2 },
    ],
    themeId: 26,
  },
  {
    id: 27,
    gridSize: 9,
    nodes: [
      { number: 1, position: { x: 1, y: 0 } },
      { number: 2, position: { x: 4, y: 0 } },
      { number: 3, position: { x: 7, y: 0 } },
      { number: 4, position: { x: 8, y: 3 } },
      { number: 5, position: { x: 8, y: 6 } },
      { number: 6, position: { x: 7, y: 8 } },
      { number: 7, position: { x: 4, y: 8 } },
      { number: 8, position: { x: 1, y: 8 } },
    ],
    obstacles: [
      { x: 2, y: 1 },
      { x: 3, y: 1 },
      { x: 5, y: 1 },
      { x: 6, y: 2 },
      { x: 7, y: 4 },
      { x: 7, y: 5 },
      { x: 6, y: 6 },
      { x: 5, y: 7 },
      { x: 3, y: 7 },
      { x: 2, y: 6 },
      { x: 1, y: 5 },
      { x: 1, y: 3 },
      { x: 2, y: 3 },
      { x: 3, y: 2 },
      { x: 5, y: 3 },
    ],
    themeId: 27,
  },
  {
    id: 28,
    gridSize: 9,
    nodes: [
      { number: 1, position: { x: 0, y: 4 } },
      { number: 2, position: { x: 2, y: 0 } },
      { number: 3, position: { x: 4, y: 0 } },
      { number: 4, position: { x: 6, y: 0 } },
      { number: 5, position: { x: 8, y: 4 } },
      { number: 6, position: { x: 6, y: 8 } },
      { number: 7, position: { x: 4, y: 8 } },
      { number: 8, position: { x: 2, y: 8 } },
      { number: 9, position: { x: 4, y: 4 } },
    ],
    obstacles: [
      { x: 1, y: 1 },
      { x: 2, y: 1 },
      { x: 3, y: 2 },
      { x: 4, y: 2 },
      { x: 5, y: 2 },
      { x: 6, y: 2 },
      { x: 7, y: 3 },
      { x: 7, y: 5 },
      { x: 6, y: 6 },
      { x: 5, y: 7 },
      { x: 4, y: 6 },
      { x: 3, y: 7 },
      { x: 2, y: 6 },
      { x: 1, y: 5 },
      { x: 1, y: 3 },
    ],
    themeId: 28,
  },
  {
    id: 29,
    gridSize: 9,
    nodes: [
      { number: 1, position: { x: 1, y: 1 } },
      { number: 2, position: { x: 4, y: 0 } },
      { number: 3, position: { x: 7, y: 1 } },
      { number: 4, position: { x: 8, y: 4 } },
      { number: 5, position: { x: 8, y: 7 } },
      { number: 6, position: { x: 7, y: 8 } },
      { number: 7, position: { x: 4, y: 8 } },
      { number: 8, position: { x: 1, y: 8 } },
    ],
    obstacles: [
      { x: 2, y: 1 },
      { x: 3, y: 2 },
      { x: 5, y: 2 },
      { x: 6, y: 1 },
      { x: 7, y: 3 },
      { x: 7, y: 5 },
      { x: 6, y: 6 },
      { x: 5, y: 7 },
      { x: 3, y: 7 },
      { x: 2, y: 6 },
      { x: 1, y: 5 },
      { x: 1, y: 3 },
      { x: 2, y: 3 },
      { x: 3, y: 4 },
      { x: 5, y: 4 },
      { x: 6, y: 5 },
    ],
    themeId: 29,
  },
  {
    id: 30,
    gridSize: 9,
    nodes: [
      { number: 1, position: { x: 0, y: 0 } },
      { number: 2, position: { x: 3, y: 0 } },
      { number: 3, position: { x: 6, y: 0 } },
      { number: 4, position: { x: 8, y: 4 } },
      { number: 5, position: { x: 8, y: 8 } },
      { number: 6, position: { x: 4, y: 8 } },
      { number: 7, position: { x: 0, y: 8 } },
      { number: 8, position: { x: 0, y: 4 } },
    ],
    obstacles: [
      { x: 1, y: 1 },
      { x: 2, y: 2 },
      { x: 3, y: 1 },
      { x: 4, y: 2 },
      { x: 5, y: 1 },
      { x: 6, y: 2 },
      { x: 7, y: 3 },
      { x: 7, y: 5 },
      { x: 7, y: 7 },
      { x: 6, y: 6 },
      { x: 5, y: 7 },
      { x: 4, y: 6 },
      { x: 3, y: 7 },
      { x: 2, y: 6 },
      { x: 1, y: 5 },
      { x: 1, y: 3 },
      { x: 2, y: 3 },
      { x: 3, y: 4 },
      { x: 5, y: 4 },
      { x: 6, y: 5 },
    ],
    themeId: 30,
  },
];
