import type { Level } from "../ZipTypes";

export const LEVELS_HARD1: Level[] = [
  {
    id: 21,
    gridSize: 9,
    nodes: [
      { number: 1, position: { x: 1, y: 1 } },
      { number: 2, position: { x: 7, y: 1 } },
      { number: 3, position: { x: 8, y: 4 } },
      { number: 4, position: { x: 7, y: 7 } },
      { number: 5, position: { x: 1, y: 7 } },
      { number: 6, position: { x: 0, y: 4 } },
      { number: 7, position: { x: 4, y: 0 } },
      { number: 8, position: { x: 4, y: 8 } },
    ],
    obstacles: [
      { x: 2, y: 2 },
      { x: 4, y: 2 },
      { x: 6, y: 3 },
      { x: 7, y: 5 },
      { x: 5, y: 6 },
      { x: 2, y: 5 },
      { x: 1, y: 3 },
      { x: 3, y: 4 },
    ],
    themeId: 21,
  },
  {
    id: 22,
    gridSize: 9,
    nodes: [
      { number: 1, position: { x: 0, y: 4 } },
      { number: 2, position: { x: 2, y: 0 } },
      { number: 3, position: { x: 5, y: 0 } },
      { number: 4, position: { x: 8, y: 2 } },
      { number: 5, position: { x: 8, y: 6 } },
      { number: 6, position: { x: 6, y: 8 } },
      { number: 7, position: { x: 2, y: 8 } },
      { number: 8, position: { x: 0, y: 6 } },
    ],
    obstacles: [
      { x: 1, y: 1 },
      { x: 3, y: 1 },
      { x: 5, y: 2 },
      { x: 6, y: 4 },
      { x: 7, y: 6 },
      { x: 5, y: 7 },
      { x: 3, y: 7 },
      { x: 2, y: 5 },
      { x: 1, y: 3 },
      { x: 4, y: 4 },
    ],
    themeId: 22,
  },
  {
    id: 23,
    gridSize: 9,
    nodes: [
      { number: 1, position: { x: 1, y: 0 } },
      { number: 2, position: { x: 4, y: 1 } },
      { number: 3, position: { x: 7, y: 0 } },
      { number: 4, position: { x: 8, y: 3 } },
      { number: 5, position: { x: 8, y: 6 } },
      { number: 6, position: { x: 5, y: 8 } },
      { number: 7, position: { x: 2, y: 8 } },
      { number: 8, position: { x: 0, y: 5 } },
    ],
    obstacles: [
      { x: 2, y: 1 },
      { x: 3, y: 2 },
      { x: 5, y: 2 },
      { x: 6, y: 3 },
      { x: 7, y: 5 },
      { x: 6, y: 6 },
      { x: 4, y: 7 },
      { x: 2, y: 6 },
      { x: 1, y: 4 },
      { x: 3, y: 4 },
    ],
    themeId: 23,
  },
  {
    id: 24,
    gridSize: 9,
    nodes: [
      { number: 1, position: { x: 0, y: 0 } },
      { number: 2, position: { x: 3, y: 0 } },
      { number: 3, position: { x: 6, y: 0 } },
      { number: 4, position: { x: 8, y: 4 } },
      { number: 5, position: { x: 6, y: 8 } },
      { number: 6, position: { x: 3, y: 8 } },
      { number: 7, position: { x: 0, y: 8 } },
      { number: 8, position: { x: 0, y: 4 } },
    ],
    obstacles: [
      { x: 1, y: 1 },
      { x: 2, y: 2 },
      { x: 4, y: 1 },
      { x: 5, y: 2 },
      { x: 6, y: 3 },
      { x: 7, y: 5 },
      { x: 6, y: 6 },
      { x: 5, y: 7 },
      { x: 3, y: 6 },
      { x: 2, y: 5 },
      { x: 1, y: 4 },
      { x: 2, y: 3 },
    ],
    themeId: 24,
  },
  {
    id: 25,
    gridSize: 9,
    nodes: [
      { number: 1, position: { x: 2, y: 1 } },
      { number: 2, position: { x: 6, y: 1 } },
      { number: 3, position: { x: 8, y: 3 } },
      { number: 4, position: { x: 8, y: 6 } },
      { number: 5, position: { x: 6, y: 8 } },
      { number: 6, position: { x: 2, y: 8 } },
      { number: 7, position: { x: 0, y: 6 } },
      { number: 8, position: { x: 0, y: 3 } },
    ],
    obstacles: [
      { x: 1, y: 1 },
      { x: 3, y: 1 },
      { x: 4, y: 2 },
      { x: 6, y: 2 },
      { x: 7, y: 4 },
      { x: 7, y: 6 },
      { x: 6, y: 7 },
      { x: 4, y: 7 },
      { x: 2, y: 6 },
      { x: 1, y: 5 },
      { x: 1, y: 3 },
      { x: 2, y: 2 },
      { x: 4, y: 4 },
    ],
    themeId: 25,
  },
];
