import type { Level } from "../ZipTypes";

export const LEVELS_MEDIUM: Level[] = [
  {
    id: 11,
    gridSize: 7,
    nodes: [
      { number: 1, position: { x: 1, y: 1 } },
      { number: 2, position: { x: 5, y: 1 } },
      { number: 3, position: { x: 5, y: 5 } },
      { number: 4, position: { x: 1, y: 5 } },
      { number: 5, position: { x: 3, y: 3 } },
      { number: 6, position: { x: 6, y: 6 } },
    ],
    obstacles: [
      { x: 2, y: 2 },
      { x: 4, y: 4 },
    ],
    themeId: 11,
  },
  {
    id: 12,
    gridSize: 7,
    nodes: [
      { number: 1, position: { x: 0, y: 2 } },
      { number: 2, position: { x: 3, y: 0 } },
      { number: 3, position: { x: 6, y: 2 } },
      { number: 4, position: { x: 6, y: 4 } },
      { number: 5, position: { x: 3, y: 6 } },
      { number: 6, position: { x: 0, y: 4 } },
    ],
    obstacles: [
      { x: 2, y: 1 },
      { x: 4, y: 1 },
      { x: 5, y: 3 },
      { x: 2, y: 5 },
    ],
    themeId: 12,
  },
  {
    id: 13,
    gridSize: 7,
    nodes: [
      { number: 1, position: { x: 1, y: 0 } },
      { number: 2, position: { x: 3, y: 1 } },
      { number: 3, position: { x: 5, y: 0 } },
      { number: 4, position: { x: 6, y: 3 } },
      { number: 5, position: { x: 4, y: 5 } },
      { number: 6, position: { x: 1, y: 6 } },
    ],
    obstacles: [
      { x: 0, y: 3 },
      { x: 2, y: 2 },
      { x: 3, y: 4 },
      { x: 5, y: 5 },
    ],
    themeId: 13,
  },
  {
    id: 14,
    gridSize: 7,
    nodes: [
      { number: 1, position: { x: 2, y: 1 } },
      { number: 2, position: { x: 5, y: 1 } },
      { number: 3, position: { x: 6, y: 3 } },
      { number: 4, position: { x: 5, y: 5 } },
      { number: 5, position: { x: 1, y: 5 } },
      { number: 6, position: { x: 0, y: 2 } },
    ],
    obstacles: [
      { x: 1, y: 2 },
      { x: 3, y: 1 },
      { x: 4, y: 3 },
      { x: 3, y: 5 },
      { x: 2, y: 4 },
    ],
    themeId: 14,
  },
  {
    id: 15,
    gridSize: 7,
    nodes: [
      { number: 1, position: { x: 0, y: 0 } },
      { number: 2, position: { x: 3, y: 0 } },
      { number: 3, position: { x: 6, y: 0 } },
      { number: 4, position: { x: 6, y: 6 } },
      { number: 5, position: { x: 3, y: 6 } },
      { number: 6, position: { x: 0, y: 6 } },
    ],
    obstacles: [
      { x: 1, y: 1 },
      { x: 2, y: 2 },
      { x: 3, y: 3 },
      { x: 4, y: 4 },
      { x: 5, y: 5 },
    ],
    themeId: 15,
  },
  {
    id: 16,
    gridSize: 8,
    nodes: [
      { number: 1, position: { x: 1, y: 1 } },
      { number: 2, position: { x: 6, y: 1 } },
      { number: 3, position: { x: 6, y: 6 } },
      { number: 4, position: { x: 1, y: 6 } },
      { number: 5, position: { x: 3, y: 3 } },
      { number: 6, position: { x: 0, y: 0 } },
      { number: 7, position: { x: 7, y: 7 } },
    ],
    obstacles: [
      { x: 2, y: 2 },
      { x: 4, y: 3 },
      { x: 5, y: 4 },
      { x: 3, y: 5 },
      { x: 2, y: 4 },
    ],
    themeId: 16,
  },
  {
    id: 17,
    gridSize: 8,
    nodes: [
      { number: 1, position: { x: 0, y: 3 } },
      { number: 2, position: { x: 2, y: 0 } },
      { number: 3, position: { x: 5, y: 0 } },
      { number: 4, position: { x: 7, y: 2 } },
      { number: 5, position: { x: 7, y: 5 } },
      { number: 6, position: { x: 4, y: 7 } },
      { number: 7, position: { x: 1, y: 7 } },
    ],
    obstacles: [
      { x: 1, y: 1 },
      { x: 2, y: 2 },
      { x: 4, y: 2 },
      { x: 5, y: 4 },
      { x: 6, y: 5 },
      { x: 4, y: 6 },
      { x: 2, y: 5 },
    ],
    themeId: 17,
  },
  {
    id: 18,
    gridSize: 8,
    nodes: [
      { number: 1, position: { x: 3, y: 0 } },
      { number: 2, position: { x: 6, y: 1 } },
      { number: 3, position: { x: 7, y: 4 } },
      { number: 4, position: { x: 5, y: 7 } },
      { number: 5, position: { x: 2, y: 7 } },
      { number: 6, position: { x: 0, y: 5 } },
      { number: 7, position: { x: 0, y: 1 } },
    ],
    obstacles: [
      { x: 2, y: 2 },
      { x: 4, y: 1 },
      { x: 5, y: 3 },
      { x: 6, y: 5 },
      { x: 4, y: 6 },
      { x: 2, y: 5 },
      { x: 1, y: 3 },
    ],
    themeId: 18,
  },
  {
    id: 19,
    gridSize: 8,
    nodes: [
      { number: 1, position: { x: 1, y: 0 } },
      { number: 2, position: { x: 4, y: 0 } },
      { number: 3, position: { x: 6, y: 2 } },
      { number: 4, position: { x: 7, y: 5 } },
      { number: 5, position: { x: 5, y: 7 } },
      { number: 6, position: { x: 2, y: 7 } },
      { number: 7, position: { x: 0, y: 4 } },
    ],
    obstacles: [
      { x: 2, y: 1 },
      { x: 3, y: 2 },
      { x: 5, y: 2 },
      { x: 6, y: 4 },
      { x: 5, y: 5 },
      { x: 3, y: 6 },
      { x: 1, y: 5 },
    ],
    themeId: 19,
  },
  {
    id: 20,
    gridSize: 8,
    nodes: [
      { number: 1, position: { x: 0, y: 0 } },
      { number: 2, position: { x: 3, y: 1 } },
      { number: 3, position: { x: 5, y: 0 } },
      { number: 4, position: { x: 7, y: 3 } },
      { number: 5, position: { x: 6, y: 6 } },
      { number: 6, position: { x: 3, y: 7 } },
      { number: 7, position: { x: 0, y: 7 } },
    ],
    obstacles: [
      { x: 1, y: 1 },
      { x: 2, y: 2 },
      { x: 4, y: 3 },
      { x: 5, y: 4 },
      { x: 5, y: 5 },
      { x: 4, y: 6 },
      { x: 2, y: 5 },
      { x: 1, y: 3 },
    ],
    themeId: 20,
  },
];
