export const COLORS = {
  SCREEN_BG: '#0F0F0F',
  GRID_BG: '#1A1A1A',
  CELL_DEFAULT_BG: '#1A1A1A',
  CELL_BORDER: 'rgba(255,255,255,0.18)',

  BARRIER_COLOR: '#FFFFFF',
  BARRIER_WIDTH: 4,

  NODE_BORDER: '#FFFFFF',
  NODE_BG: '#1A1A1A',
  NODE_TEXT: '#FFFFFF',
  NODE_ACTIVE_BG: '#2D5A2D',
  NODE_ACTIVE_BORDER: '#FFFFFF',

  PATH_COLORS: [
    '#22C55E',
    '#06B6D4',
    '#8B5CF6',
    '#F97316',
    '#EC4899',
    '#EAB308',
    '#3B82F6',
    '#10B981',
  ],
  PATH_OPACITY: 0.85,
  HINT_PATH_OPACITY: 0.6,

  TIMER_COLOR: '#FFFFFF',
  TIMER_ICON: '#FFFFFF',

  UNDO_BTN_BG: '#2A2A2A',
  UNDO_BTN_TEXT: '#888888',
  HINT_BTN_BG: '#1A1A1A',
  HINT_BTN_BORDER: '#FFFFFF',
  HINT_BTN_TEXT: '#FFFFFF',

  RESET_BTN_BG: '#2A2A2A',
  RESET_BTN_BORDER: '#666666',
  RESET_BTN_TEXT: '#FFFFFF',

  MESSAGE_BG: '#1E1E1E',
  MESSAGE_TEXT: '#CCCCCC',
  MESSAGE_BORDER: '#333333',

  HOWTOPLAY_BG: '#1E1E1E',
  HOWTOPLAY_HEADER: '#FFFFFF',
}

export const GRID_PADDING = 16
export const HINT_ARROW_DISPLAY_TIME = 3000
export const HINT_EXTENSION_STEPS = 3
