import type { KenKenLevel } from './KenKenTypes';

export const KENKEN_LEVELS: KenKenLevel[] = [
  {
    id: 1,
    gridSize: 3,
    difficulty: 'easy',
    solution: [
      [1, 2, 3],
      [3, 1, 2],
      [2, 3, 1],
    ],
    cages: [
      { id: 'L1_C1', cells: [{ row: 0, col: 0 }, { row: 0, col: 1 }], target: 3, operation: '+' },
      { id: 'L1_C2', cells: [{ row: 0, col: 2 }], target: 3, operation: 'given' },
      { id: 'L1_C3', cells: [{ row: 1, col: 0 }], target: 3, operation: 'given' },
      { id: 'L1_C4', cells: [{ row: 1, col: 1 }, { row: 1, col: 2 }], target: 1, operation: '-' },
      { id: 'L1_C5', cells: [{ row: 2, col: 0 }, { row: 2, col: 1 }], target: 5, operation: '+' },
      { id: 'L1_C6', cells: [{ row: 2, col: 2 }], target: 1, operation: 'given' },
    ],
  },
  {
    id: 2,
    gridSize: 3,
    difficulty: 'easy',
    solution: [
      [2, 3, 1],
      [1, 2, 3],
      [3, 1, 2],
    ],
    cages: [
      { id: 'L2_C1', cells: [{ row: 0, col: 0 }, { row: 0, col: 1 }], target: 5, operation: '+' },
      { id: 'L2_C2', cells: [{ row: 0, col: 2 }], target: 1, operation: 'given' },
      { id: 'L2_C3', cells: [{ row: 1, col: 0 }, { row: 1, col: 1 }], target: 3, operation: '+' },
      { id: 'L2_C4', cells: [{ row: 1, col: 2 }], target: 3, operation: 'given' },
      { id: 'L2_C5', cells: [{ row: 2, col: 0 }, { row: 2, col: 1 }], target: 4, operation: '+' },
      { id: 'L2_C6', cells: [{ row: 2, col: 2 }], target: 2, operation: 'given' },
    ],
  },
  {
    id: 3,
    gridSize: 3,
    difficulty: 'easy',
    solution: [
      [3, 1, 2],
      [2, 3, 1],
      [1, 2, 3],
    ],
    cages: [
      { id: 'L3_C1', cells: [{ row: 0, col: 0 }], target: 3, operation: 'given' },
      { id: 'L3_C2', cells: [{ row: 0, col: 1 }, { row: 0, col: 2 }], target: 3, operation: '+' },
      { id: 'L3_C3', cells: [{ row: 1, col: 0 }, { row: 1, col: 1 }], target: 5, operation: '+' },
      { id: 'L3_C4', cells: [{ row: 1, col: 2 }], target: 1, operation: 'given' },
      { id: 'L3_C5', cells: [{ row: 2, col: 0 }, { row: 2, col: 1 }], target: 3, operation: '+' },
      { id: 'L3_C6', cells: [{ row: 2, col: 2 }], target: 3, operation: 'given' },
    ],
  },
  {
    id: 4,
    gridSize: 3,
    difficulty: 'easy',
    solution: [
      [1, 3, 2],
      [2, 1, 3],
      [3, 2, 1],
    ],
    cages: [
      { id: 'L4_C1', cells: [{ row: 0, col: 0 }, { row: 0, col: 1 }], target: 4, operation: '+' },
      { id: 'L4_C2', cells: [{ row: 0, col: 2 }], target: 2, operation: 'given' },
      { id: 'L4_C3', cells: [{ row: 1, col: 0 }], target: 2, operation: 'given' },
      { id: 'L4_C4', cells: [{ row: 1, col: 1 }, { row: 1, col: 2 }], target: 4, operation: '+' },
      { id: 'L4_C5', cells: [{ row: 2, col: 0 }, { row: 2, col: 1 }], target: 5, operation: '+' },
      { id: 'L4_C6', cells: [{ row: 2, col: 2 }], target: 1, operation: 'given' },
    ],
  },
  {
    id: 5,
    gridSize: 3,
    difficulty: 'easy',
    solution: [
      [2, 1, 3],
      [3, 2, 1],
      [1, 3, 2],
    ],
    cages: [
      { id: 'L5_C1', cells: [{ row: 0, col: 0 }], target: 2, operation: 'given' },
      { id: 'L5_C2', cells: [{ row: 0, col: 1 }, { row: 0, col: 2 }], target: 4, operation: '+' },
      { id: 'L5_C3', cells: [{ row: 1, col: 0 }, { row: 1, col: 1 }], target: 5, operation: '+' },
      { id: 'L5_C4', cells: [{ row: 1, col: 2 }], target: 1, operation: 'given' },
      { id: 'L5_C5', cells: [{ row: 2, col: 0 }, { row: 2, col: 1 }], target: 4, operation: '+' },
      { id: 'L5_C6', cells: [{ row: 2, col: 2 }], target: 2, operation: 'given' },
    ],
  },
  {
    id: 6,
    gridSize: 4,
    difficulty: 'easy',
    solution: [
      [1, 2, 3, 4],
      [4, 3, 2, 1],
      [2, 4, 1, 3],
      [3, 1, 4, 2],
    ],
    cages: [
      { id: 'L6_C1', cells: [{ row: 0, col: 0 }, { row: 0, col: 1 }], target: 3, operation: '+' },
      { id: 'L6_C2', cells: [{ row: 0, col: 2 }, { row: 0, col: 3 }], target: 7, operation: '+' },
      { id: 'L6_C3', cells: [{ row: 1, col: 0 }, { row: 1, col: 1 }], target: 7, operation: '+' },
      { id: 'L6_C4', cells: [{ row: 1, col: 2 }, { row: 1, col: 3 }], target: 3, operation: '+' },
      { id: 'L6_C5', cells: [{ row: 2, col: 0 }, { row: 2, col: 1 }], target: 6, operation: '+' },
      { id: 'L6_C6', cells: [{ row: 2, col: 2 }, { row: 2, col: 3 }], target: 4, operation: '+' },
      { id: 'L6_C7', cells: [{ row: 3, col: 0 }, { row: 3, col: 1 }], target: 4, operation: '+' },
      { id: 'L6_C8', cells: [{ row: 3, col: 2 }, { row: 3, col: 3 }], target: 6, operation: '+' },
    ],
  },
  {
    id: 7,
    gridSize: 4,
    difficulty: 'easy',
    solution: [
      [3, 1, 4, 2],
      [1, 4, 2, 3],
      [2, 3, 1, 4],
      [4, 2, 3, 1],
    ],
    cages: [
      { id: 'L7_C1', cells: [{ row: 0, col: 0 }, { row: 0, col: 1 }, { row: 0, col: 2 }], target: 8, operation: '+' },
      { id: 'L7_C2', cells: [{ row: 0, col: 3 }], target: 2, operation: '+' },
      { id: 'L7_C3', cells: [{ row: 1, col: 0 }, { row: 1, col: 1 }], target: 5, operation: '+' },
      { id: 'L7_C4', cells: [{ row: 1, col: 2 }, { row: 1, col: 3 }], target: 5, operation: '+' },
      { id: 'L7_C5', cells: [{ row: 2, col: 0 }, { row: 2, col: 1 }], target: 5, operation: '+' },
      { id: 'L7_C6', cells: [{ row: 2, col: 2 }, { row: 2, col: 3 }], target: 5, operation: '+' },
      { id: 'L7_C7', cells: [{ row: 3, col: 0 }, { row: 3, col: 1 }], target: 6, operation: '+' },
      { id: 'L7_C8', cells: [{ row: 3, col: 2 }, { row: 3, col: 3 }], target: 4, operation: '+' },
    ],
  },
  {
    id: 8,
    gridSize: 4,
    difficulty: 'easy',
    solution: [
      [3, 2, 1, 4],
      [1, 4, 3, 2],
      [2, 3, 4, 1],
      [4, 1, 2, 3],
    ],
    cages: [
      { id: 'L8_C1', cells: [{ row: 0, col: 0 }], target: 3, operation: 'given' },
      { id: 'L8_C2', cells: [{ row: 0, col: 1 }, { row: 0, col: 2 }], target: 3, operation: '+' },
      { id: 'L8_C3', cells: [{ row: 0, col: 3 }], target: 4, operation: 'given' },
      { id: 'L8_C4', cells: [{ row: 1, col: 0 }, { row: 1, col: 1 }], target: 5, operation: '+' },
      { id: 'L8_C5', cells: [{ row: 1, col: 2 }, { row: 1, col: 3 }], target: 5, operation: '+' },
      { id: 'L8_C6', cells: [{ row: 2, col: 0 }, { row: 2, col: 1 }], target: 5, operation: '+' },
      { id: 'L8_C7', cells: [{ row: 2, col: 2 }, { row: 2, col: 3 }], target: 5, operation: '+' },
      { id: 'L8_C8', cells: [{ row: 3, col: 0 }, { row: 3, col: 1 }], target: 5, operation: '+' },
      { id: 'L8_C9', cells: [{ row: 3, col: 2 }, { row: 3, col: 3 }], target: 5, operation: '+' },
    ],
  },
  {
    id: 9,
    gridSize: 4,
    difficulty: 'medium',
    solution: [
      [2, 4, 1, 3],
      [3, 1, 4, 2],
      [1, 3, 2, 4],
      [4, 2, 3, 1],
    ],
    cages: [
      { id: 'L9_C1', cells: [{ row: 0, col: 0 }, { row: 1, col: 0 }], target: 5, operation: '+' },
      { id: 'L9_C2', cells: [{ row: 0, col: 1 }, { row: 0, col: 2 }], target: 5, operation: '+' },
      { id: 'L9_C3', cells: [{ row: 0, col: 3 }, { row: 1, col: 3 }], target: 5, operation: '+' },
      { id: 'L9_C4', cells: [{ row: 1, col: 1 }, { row: 1, col: 2 }], target: 5, operation: '+' },
      { id: 'L9_C5', cells: [{ row: 2, col: 0 }, { row: 3, col: 0 }], target: 5, operation: '+' },
      { id: 'L9_C6', cells: [{ row: 2, col: 1 }, { row: 2, col: 2 }], target: 5, operation: '+' },
      { id: 'L9_C7', cells: [{ row: 2, col: 3 }, { row: 3, col: 3 }], target: 5, operation: '+' },
      { id: 'L9_C8', cells: [{ row: 3, col: 1 }, { row: 3, col: 2 }], target: 5, operation: '+' },
    ],
  },
  {
    id: 10,
    gridSize: 4,
    difficulty: 'medium',
    solution: [
      [1, 3, 4, 2],
      [2, 4, 1, 3],
      [4, 2, 3, 1],
      [3, 1, 2, 4],
    ],
    cages: [
      { id: 'L10_C1', cells: [{ row: 0, col: 0 }, { row: 0, col: 1 }, { row: 1, col: 1 }], target: 8, operation: '+' },
      { id: 'L10_C2', cells: [{ row: 0, col: 2 }, { row: 0, col: 3 }], target: 6, operation: '+' },
      { id: 'L10_C3', cells: [{ row: 1, col: 0 }, { row: 2, col: 0 }], target: 6, operation: '+' },
      { id: 'L10_C4', cells: [{ row: 1, col: 2 }, { row: 1, col: 3 }], target: 4, operation: '+' },
      { id: 'L10_C5', cells: [{ row: 2, col: 1 }, { row: 2, col: 2 }], target: 5, operation: '+' },
      { id: 'L10_C6', cells: [{ row: 2, col: 3 }, { row: 3, col: 3 }], target: 5, operation: '+' },
      { id: 'L10_C7', cells: [{ row: 3, col: 0 }, { row: 3, col: 1 }], target: 4, operation: '+' },
      { id: 'L10_C8', cells: [{ row: 3, col: 2 }], target: 2, operation: 'given' },
    ],
  },
  {
    id: 11,
    gridSize: 4,
    difficulty: 'medium',
    solution: [
      [2, 3, 1, 4],
      [4, 1, 3, 2],
      [1, 2, 4, 3],
      [3, 4, 2, 1],
    ],
    cages: [
      { id: 'L11_C1', cells: [{ row: 0, col: 0 }, { row: 0, col: 1 }], target: 1, operation: '-' },
      { id: 'L11_C2', cells: [{ row: 0, col: 2 }, { row: 0, col: 3 }], target: 5, operation: '+' },
      { id: 'L11_C3', cells: [{ row: 1, col: 0 }, { row: 1, col: 1 }], target: 3, operation: '-' },
      { id: 'L11_C4', cells: [{ row: 1, col: 2 }, { row: 1, col: 3 }], target: 5, operation: '+' },
      { id: 'L11_C5', cells: [{ row: 2, col: 0 }, { row: 2, col: 1 }], target: 3, operation: '+' },
      { id: 'L11_C6', cells: [{ row: 2, col: 2 }, { row: 2, col: 3 }], target: 1, operation: '-' },
      { id: 'L11_C7', cells: [{ row: 3, col: 0 }, { row: 3, col: 1 }], target: 1, operation: '-' },
      { id: 'L11_C8', cells: [{ row: 3, col: 2 }, { row: 3, col: 3 }], target: 3, operation: '+' },
    ],
  },
  {
    id: 12,
    gridSize: 4,
    difficulty: 'medium',
    solution: [
      [1, 2, 4, 3],
      [3, 4, 1, 2],
      [2, 1, 3, 4],
      [4, 3, 2, 1],
    ],
    cages: [
      { id: 'L12_C1', cells: [{ row: 0, col: 0 }, { row: 0, col: 1 }], target: 3, operation: '+' },
      { id: 'L12_C2', cells: [{ row: 0, col: 2 }, { row: 0, col: 3 }], target: 1, operation: '-' },
      { id: 'L12_C3', cells: [{ row: 1, col: 0 }, { row: 1, col: 1 }], target: 7, operation: '+' },
      { id: 'L12_C4', cells: [{ row: 1, col: 2 }, { row: 1, col: 3 }], target: 3, operation: '+' },
      { id: 'L12_C5', cells: [{ row: 2, col: 0 }, { row: 2, col: 1 }], target: 3, operation: '+' },
      { id: 'L12_C6', cells: [{ row: 2, col: 2 }, { row: 2, col: 3 }], target: 1, operation: '-' },
      { id: 'L12_C7', cells: [{ row: 3, col: 0 }, { row: 3, col: 1 }], target: 1, operation: '-' },
      { id: 'L12_C8', cells: [{ row: 3, col: 2 }, { row: 3, col: 3 }], target: 3, operation: '+' },
    ],
  },
  {
    id: 13,
    gridSize: 4,
    difficulty: 'hard',
    solution: [
      [3, 2, 4, 1],
      [1, 4, 3, 2],
      [4, 1, 2, 3],
      [2, 3, 1, 4],
    ],
    cages: [
      { id: 'L13_C1', cells: [{ row: 0, col: 0 }, { row: 0, col: 1 }, { row: 1, col: 0 }], target: 6, operation: '+' },
      { id: 'L13_C2', cells: [{ row: 0, col: 2 }, { row: 0, col: 3 }], target: 5, operation: '+' },
      { id: 'L13_C3', cells: [{ row: 1, col: 1 }, { row: 1, col: 2 }], target: 7, operation: '+' },
      { id: 'L13_C4', cells: [{ row: 1, col: 3 }, { row: 2, col: 3 }], target: 5, operation: '+' },
      { id: 'L13_C5', cells: [{ row: 2, col: 0 }, { row: 3, col: 0 }], target: 6, operation: '+' },
      { id: 'L13_C6', cells: [{ row: 2, col: 1 }, { row: 2, col: 2 }], target: 3, operation: '+' },
      { id: 'L13_C7', cells: [{ row: 3, col: 1 }, { row: 3, col: 2 }], target: 4, operation: '+' },
      { id: 'L13_C8', cells: [{ row: 3, col: 3 }], target: 4, operation: 'given' },
    ],
  },
  {
    id: 14,
    gridSize: 4,
    difficulty: 'hard',
    solution: [
      [1, 4, 2, 3],
      [2, 3, 1, 4],
      [3, 1, 4, 2],
      [4, 2, 3, 1],
    ],
    cages: [
      { id: 'L14_C1', cells: [{ row: 0, col: 0 }, { row: 0, col: 1 }, { row: 1, col: 0 }], target: 7, operation: '+' },
      { id: 'L14_C2', cells: [{ row: 0, col: 2 }, { row: 0, col: 3 }], target: 6, operation: '*' },
      { id: 'L14_C3', cells: [{ row: 1, col: 1 }, { row: 1, col: 2 }], target: 2, operation: '-' },
      { id: 'L14_C4', cells: [{ row: 1, col: 3 }, { row: 2, col: 3 }], target: 6, operation: '+' },
      { id: 'L14_C5', cells: [{ row: 2, col: 0 }, { row: 3, col: 0 }], target: 7, operation: '+' },
      { id: 'L14_C6', cells: [{ row: 2, col: 1 }, { row: 2, col: 2 }], target: 5, operation: '+' },
      { id: 'L14_C7', cells: [{ row: 3, col: 1 }, { row: 3, col: 2 }], target: 1, operation: '-' },
      { id: 'L14_C8', cells: [{ row: 3, col: 3 }], target: 1, operation: '+' },
    ],
  },
  {
    id: 15,
    gridSize: 4,
    difficulty: 'hard',
    solution: [
      [1, 2, 4, 3],
      [2, 4, 3, 1],
      [3, 1, 2, 4],
      [4, 3, 1, 2],
    ],
    cages: [
      { id: 'L15_C1', cells: [{ row: 0, col: 0 }, { row: 0, col: 1 }], target: 2, operation: '/' },
      { id: 'L15_C2', cells: [{ row: 0, col: 2 }, { row: 0, col: 3 }], target: 12, operation: '*' },
      { id: 'L15_C3', cells: [{ row: 1, col: 0 }, { row: 1, col: 1 }], target: 2, operation: '/' },
      { id: 'L15_C4', cells: [{ row: 1, col: 2 }, { row: 1, col: 3 }], target: 4, operation: '+' },
      { id: 'L15_C5', cells: [{ row: 2, col: 0 }, { row: 2, col: 1 }], target: 2, operation: '-' },
      { id: 'L15_C6', cells: [{ row: 2, col: 2 }, { row: 2, col: 3 }], target: 8, operation: '*' },
      { id: 'L15_C7', cells: [{ row: 3, col: 0 }, { row: 3, col: 1 }], target: 7, operation: '+' },
      { id: 'L15_C8', cells: [{ row: 3, col: 2 }, { row: 3, col: 3 }], target: 3, operation: '+' },
    ],
  },
  {
    id: 16,
    gridSize: 4,
    difficulty: 'hard',
    solution: [
      [4, 3, 1, 2],
      [2, 1, 4, 3],
      [1, 2, 3, 4],
      [3, 4, 2, 1],
    ],
    cages: [
      { id: 'L16_C1', cells: [{ row: 0, col: 0 }, { row: 1, col: 0 }, { row: 2, col: 0 }, { row: 3, col: 0 }], target: 10, operation: '+' },
      { id: 'L16_C2', cells: [{ row: 0, col: 1 }, { row: 0, col: 2 }, { row: 0, col: 3 }], target: 6, operation: '+' },
      { id: 'L16_C3', cells: [{ row: 1, col: 1 }, { row: 1, col: 2 }, { row: 1, col: 3 }], target: 8, operation: '+' },
      { id: 'L16_C4', cells: [{ row: 2, col: 1 }, { row: 2, col: 2 }, { row: 2, col: 3 }], target: 9, operation: '+' },
      { id: 'L16_C5', cells: [{ row: 3, col: 1 }, { row: 3, col: 2 }, { row: 3, col: 3 }], target: 7, operation: '+' },
    ],
  },
  {
    id: 17,
    gridSize: 4,
    difficulty: 'hard',
    solution: [
      [1, 3, 4, 2],
      [2, 4, 1, 3],
      [4, 2, 3, 1],
      [3, 1, 2, 4],
    ],
    cages: [
      { id: 'L17_C1', cells: [{ row: 0, col: 0 }, { row: 0, col: 1 }, { row: 1, col: 1 }], target: 9, operation: '+' },
      { id: 'L17_C2', cells: [{ row: 0, col: 2 }, { row: 0, col: 3 }, { row: 1, col: 3 }], target: 9, operation: '+' },
      { id: 'L17_C3', cells: [{ row: 1, col: 0 }, { row: 2, col: 0 }], target: 2, operation: '-' },
      { id: 'L17_C4', cells: [{ row: 1, col: 2 }, { row: 2, col: 2 }], target: 4, operation: '+' },
      { id: 'L17_C5', cells: [{ row: 2, col: 1 }, { row: 2, col: 3 }], target: 2, operation: '/' },
      { id: 'L17_C6', cells: [{ row: 3, col: 0 }, { row: 3, col: 1 }, { row: 3, col: 2 }, { row: 3, col: 3 }], target: 10, operation: '+' },
    ],
  },
  {
    id: 18,
    gridSize: 4,
    difficulty: 'hard',
    solution: [
      [2, 1, 4, 3],
      [4, 3, 2, 1],
      [1, 2, 3, 4],
      [3, 4, 1, 2],
    ],
    cages: [
      { id: 'L18_C1', cells: [{ row: 0, col: 0 }, { row: 0, col: 1 }], target: 1, operation: '-' },
      { id: 'L18_C2', cells: [{ row: 0, col: 2 }, { row: 0, col: 3 }], target: 12, operation: '*' },
      { id: 'L18_C3', cells: [{ row: 1, col: 0 }, { row: 1, col: 1 }], target: 7, operation: '+' },
      { id: 'L18_C4', cells: [{ row: 1, col: 2 }, { row: 1, col: 3 }], target: 1, operation: '-' },
      { id: 'L18_C5', cells: [{ row: 2, col: 0 }, { row: 2, col: 1 }], target: 3, operation: '+' },
      { id: 'L18_C6', cells: [{ row: 2, col: 2 }, { row: 2, col: 3 }], target: 7, operation: '+' },
      { id: 'L18_C7', cells: [{ row: 3, col: 0 }, { row: 3, col: 1 }, { row: 3, col: 2 }, { row: 3, col: 3 }], target: 10, operation: '+' },
    ],
  },
  {
    id: 19,
    gridSize: 6,
    difficulty: 'medium',
    solution: [
      [1, 2, 3, 4, 5, 6],
      [4, 5, 6, 1, 2, 3],
      [2, 3, 1, 5, 6, 4],
      [5, 6, 4, 2, 3, 1],
      [3, 1, 2, 6, 4, 5],
      [6, 4, 5, 3, 1, 2],
    ],
    cages: [
      { id: 'L19_C1', cells: [{ row: 0, col: 0 }, { row: 0, col: 1 }], target: 3, operation: '+' },
      { id: 'L19_C2', cells: [{ row: 0, col: 2 }, { row: 0, col: 3 }], target: 7, operation: '+' },
      { id: 'L19_C3', cells: [{ row: 0, col: 4 }, { row: 0, col: 5 }], target: 11, operation: '+' },
      { id: 'L19_C4', cells: [{ row: 1, col: 0 }, { row: 1, col: 1 }], target: 9, operation: '+' },
      { id: 'L19_C5', cells: [{ row: 1, col: 2 }, { row: 1, col: 3 }], target: 7, operation: '+' },
      { id: 'L19_C6', cells: [{ row: 1, col: 4 }, { row: 1, col: 5 }], target: 5, operation: '+' },
      { id: 'L19_C7', cells: [{ row: 2, col: 0 }, { row: 2, col: 1 }], target: 5, operation: '+' },
      { id: 'L19_C8', cells: [{ row: 2, col: 2 }, { row: 2, col: 3 }], target: 6, operation: '+' },
      { id: 'L19_C9', cells: [{ row: 2, col: 4 }, { row: 2, col: 5 }], target: 10, operation: '+' },
      { id: 'L19_C10', cells: [{ row: 3, col: 0 }, { row: 3, col: 1 }], target: 11, operation: '+' },
      { id: 'L19_C11', cells: [{ row: 3, col: 2 }, { row: 3, col: 3 }], target: 6, operation: '+' },
      { id: 'L19_C12', cells: [{ row: 3, col: 4 }, { row: 3, col: 5 }], target: 4, operation: '+' },
      { id: 'L19_C13', cells: [{ row: 4, col: 0 }, { row: 4, col: 1 }], target: 4, operation: '+' },
      { id: 'L19_C14', cells: [{ row: 4, col: 2 }, { row: 4, col: 3 }], target: 8, operation: '+' },
      { id: 'L19_C15', cells: [{ row: 4, col: 4 }, { row: 4, col: 5 }], target: 9, operation: '+' },
      { id: 'L19_C16', cells: [{ row: 5, col: 0 }, { row: 5, col: 1 }], target: 10, operation: '+' },
      { id: 'L19_C17', cells: [{ row: 5, col: 2 }, { row: 5, col: 3 }], target: 8, operation: '+' },
      { id: 'L19_C18', cells: [{ row: 5, col: 4 }, { row: 5, col: 5 }], target: 3, operation: '+' },
    ],
  },
  {
    id: 20,
    gridSize: 6,
    difficulty: 'medium',
    solution: [
      [1, 2, 3, 4, 5, 6],
      [4, 5, 6, 1, 2, 3],
      [2, 3, 1, 5, 6, 4],
      [5, 6, 4, 2, 3, 1],
      [3, 1, 2, 6, 4, 5],
      [6, 4, 5, 3, 1, 2],
    ],
    cages: [
      { id: 'L20_C1', cells: [{ row: 0, col: 0 }, { row: 0, col: 1 }, { row: 0, col: 2 }], target: 6, operation: '+' },
      { id: 'L20_C2', cells: [{ row: 0, col: 3 }, { row: 0, col: 4 }, { row: 0, col: 5 }], target: 15, operation: '+' },
      { id: 'L20_C3', cells: [{ row: 1, col: 0 }, { row: 1, col: 1 }], target: 9, operation: '+' },
      { id: 'L20_C4', cells: [{ row: 1, col: 2 }, { row: 1, col: 3 }], target: 7, operation: '+' },
      { id: 'L20_C5', cells: [{ row: 1, col: 4 }, { row: 1, col: 5 }], target: 5, operation: '+' },
      { id: 'L20_C6', cells: [{ row: 2, col: 0 }, { row: 2, col: 1 }, { row: 2, col: 2 }], target: 6, operation: '+' },
      { id: 'L20_C7', cells: [{ row: 2, col: 3 }, { row: 2, col: 4 }, { row: 2, col: 5 }], target: 15, operation: '+' },
      { id: 'L20_C8', cells: [{ row: 3, col: 0 }, { row: 3, col: 1 }], target: 11, operation: '+' },
      { id: 'L20_C9', cells: [{ row: 3, col: 2 }, { row: 3, col: 3 }], target: 6, operation: '+' },
      { id: 'L20_C10', cells: [{ row: 3, col: 4 }, { row: 3, col: 5 }], target: 4, operation: '+' },
      { id: 'L20_C11', cells: [{ row: 4, col: 0 }, { row: 4, col: 1 }, { row: 4, col: 2 }], target: 6, operation: '+' },
      { id: 'L20_C12', cells: [{ row: 4, col: 3 }, { row: 4, col: 4 }, { row: 4, col: 5 }], target: 15, operation: '+' },
      { id: 'L20_C13', cells: [{ row: 5, col: 0 }, { row: 5, col: 1 }], target: 10, operation: '+' },
      { id: 'L20_C14', cells: [{ row: 5, col: 2 }, { row: 5, col: 3 }, { row: 5, col: 4 }], target: 9, operation: '+' },
      { id: 'L20_C15', cells: [{ row: 5, col: 5 }], target: 2, operation: '+' },
    ],
  },
  {
    id: 21,
    gridSize: 6,
    difficulty: 'medium',
    solution: [
      [5, 6, 1, 2, 3, 4],
      [2, 3, 4, 5, 6, 1],
      [1, 4, 2, 6, 5, 3],
      [6, 2, 3, 1, 4, 5],
      [3, 5, 6, 4, 1, 2],
      [4, 1, 5, 3, 2, 6],
    ],
    cages: [
      { id: 'L21_C1', cells: [{ row: 0, col: 0 }, { row: 1, col: 0 }], target: 7, operation: '+' },
      { id: 'L21_C2', cells: [{ row: 0, col: 1 }, { row: 0, col: 2 }, { row: 0, col: 3 }], target: 9, operation: '+' },
      { id: 'L21_C3', cells: [{ row: 0, col: 4 }, { row: 0, col: 5 }, { row: 1, col: 5 }], target: 11, operation: '+' },
      { id: 'L21_C4', cells: [{ row: 1, col: 1 }, { row: 1, col: 2 }], target: 7, operation: '+' },
      { id: 'L21_C5', cells: [{ row: 1, col: 3 }, { row: 1, col: 4 }], target: 11, operation: '+' },
      { id: 'L21_C6', cells: [{ row: 2, col: 0 }, { row: 2, col: 1 }], target: 5, operation: '+' },
      { id: 'L21_C7', cells: [{ row: 2, col: 2 }, { row: 2, col: 3 }], target: 8, operation: '+' },
      { id: 'L21_C8', cells: [{ row: 2, col: 4 }, { row: 2, col: 5 }], target: 8, operation: '+' },
      { id: 'L21_C9', cells: [{ row: 3, col: 0 }, { row: 3, col: 1 }], target: 8, operation: '+' },
      { id: 'L21_C10', cells: [{ row: 3, col: 2 }, { row: 3, col: 3 }], target: 4, operation: '+' },
      { id: 'L21_C11', cells: [{ row: 3, col: 4 }, { row: 3, col: 5 }], target: 9, operation: '+' },
      { id: 'L21_C12', cells: [{ row: 4, col: 0 }, { row: 4, col: 1 }], target: 8, operation: '+' },
      { id: 'L21_C13', cells: [{ row: 4, col: 2 }, { row: 4, col: 3 }], target: 10, operation: '+' },
      { id: 'L21_C14', cells: [{ row: 4, col: 4 }, { row: 4, col: 5 }], target: 3, operation: '+' },
      { id: 'L21_C15', cells: [{ row: 5, col: 0 }, { row: 5, col: 1 }], target: 5, operation: '+' },
      { id: 'L21_C16', cells: [{ row: 5, col: 2 }, { row: 5, col: 3 }, { row: 5, col: 4 }, { row: 5, col: 5 }], target: 16, operation: '+' },
    ],
  },
  {
    id: 22,
    gridSize: 6,
    difficulty: 'medium',
    solution: [
      [1, 2, 3, 4, 5, 6],
      [2, 3, 4, 5, 6, 1],
      [3, 4, 5, 6, 1, 2],
      [4, 5, 6, 1, 2, 3],
      [5, 6, 1, 2, 3, 4],
      [6, 1, 2, 3, 4, 5],
    ],
    cages: [
      { id: 'L22_C1', cells: [{ row: 0, col: 0 }, { row: 0, col: 1 }, { row: 1, col: 1 }], target: 7, operation: '+' },
      { id: 'L22_C2', cells: [{ row: 0, col: 2 }, { row: 0, col: 3 }], target: 7, operation: '+' },
      { id: 'L22_C3', cells: [{ row: 0, col: 4 }, { row: 0, col: 5 }], target: 11, operation: '+' },
      { id: 'L22_C4', cells: [{ row: 1, col: 0 }, { row: 2, col: 0 }], target: 5, operation: '+' },
      { id: 'L22_C5', cells: [{ row: 1, col: 2 }, { row: 1, col: 3 }], target: 9, operation: '+' },
      { id: 'L22_C6', cells: [{ row: 1, col: 4 }, { row: 1, col: 5 }], target: 7, operation: '+' },
      { id: 'L22_C7', cells: [{ row: 2, col: 1 }, { row: 2, col: 2 }], target: 9, operation: '+' },
      { id: 'L22_C8', cells: [{ row: 2, col: 3 }, { row: 2, col: 4 }, { row: 2, col: 5 }], target: 9, operation: '+' },
      { id: 'L22_C9', cells: [{ row: 3, col: 0 }, { row: 3, col: 1 }], target: 9, operation: '+' },
      { id: 'L22_C10', cells: [{ row: 3, col: 2 }, { row: 3, col: 3 }], target: 7, operation: '+' },
      { id: 'L22_C11', cells: [{ row: 3, col: 4 }, { row: 3, col: 5 }], target: 5, operation: '+' },
      { id: 'L22_C12', cells: [{ row: 4, col: 0 }, { row: 4, col: 1 }], target: 11, operation: '+' },
      { id: 'L22_C13', cells: [{ row: 4, col: 2 }, { row: 4, col: 3 }], target: 3, operation: '+' },
      { id: 'L22_C14', cells: [{ row: 4, col: 4 }, { row: 4, col: 5 }], target: 7, operation: '+' },
      { id: 'L22_C15', cells: [{ row: 5, col: 0 }, { row: 5, col: 1 }], target: 7, operation: '+' },
      { id: 'L22_C16', cells: [{ row: 5, col: 2 }, { row: 5, col: 3 }, { row: 5, col: 4 }, { row: 5, col: 5 }], target: 14, operation: '+' },
    ],
  },
  {
    id: 23,
    gridSize: 6,
    difficulty: 'medium',
    solution: [
      [1, 2, 3, 4, 5, 6],
      [2, 3, 4, 5, 6, 1],
      [3, 4, 5, 6, 1, 2],
      [4, 5, 6, 1, 2, 3],
      [5, 6, 1, 2, 3, 4],
      [6, 1, 2, 3, 4, 5],
    ],
    cages: [
      { id: 'L23_C1', cells: [{ row: 0, col: 0 }, { row: 0, col: 1 }, { row: 1, col: 0 }], target: 5, operation: '+' },
      { id: 'L23_C2', cells: [{ row: 0, col: 2 }, { row: 0, col: 3 }], target: 7, operation: '+' },
      { id: 'L23_C3', cells: [{ row: 0, col: 4 }, { row: 0, col: 5 }], target: 11, operation: '+' },
      { id: 'L23_C4', cells: [{ row: 1, col: 1 }, { row: 1, col: 2 }, { row: 2, col: 1 }], target: 12, operation: '+' },
      { id: 'L23_C5', cells: [{ row: 1, col: 3 }, { row: 1, col: 4 }], target: 11, operation: '+' },
      { id: 'L23_C6', cells: [{ row: 1, col: 5 }, { row: 2, col: 5 }], target: 3, operation: '+' },
      { id: 'L23_C7', cells: [{ row: 2, col: 0 }, { row: 3, col: 0 }], target: 7, operation: '+' },
      { id: 'L23_C8', cells: [{ row: 2, col: 2 }, { row: 2, col: 3 }], target: 11, operation: '+' },
      { id: 'L23_C9', cells: [{ row: 2, col: 4 }, { row: 3, col: 4 }], target: 3, operation: '+' },
      { id: 'L23_C10', cells: [{ row: 3, col: 1 }, { row: 3, col: 2 }], target: 11, operation: '+' },
      { id: 'L23_C11', cells: [{ row: 3, col: 3 }, { row: 3, col: 5 }], target: 4, operation: '+' },
      { id: 'L23_C12', cells: [{ row: 4, col: 0 }, { row: 4, col: 1 }], target: 11, operation: '+' },
      { id: 'L23_C13', cells: [{ row: 4, col: 2 }, { row: 4, col: 3 }], target: 3, operation: '+' },
      { id: 'L23_C14', cells: [{ row: 4, col: 4 }, { row: 4, col: 5 }], target: 7, operation: '+' },
      { id: 'L23_C15', cells: [{ row: 5, col: 0 }, { row: 5, col: 1 }], target: 7, operation: '+' },
      { id: 'L23_C16', cells: [{ row: 5, col: 2 }, { row: 5, col: 3 }, { row: 5, col: 4 }, { row: 5, col: 5 }], target: 14, operation: '+' },
    ],
  },
  {
    id: 24,
    gridSize: 6,
    difficulty: 'hard',
    solution: [
      [1, 2, 3, 4, 5, 6],
      [4, 5, 6, 3, 2, 1],
      [2, 3, 1, 5, 6, 4],
      [5, 6, 4, 2, 1, 3],
      [3, 1, 2, 6, 4, 5],
      [6, 4, 5, 1, 3, 2],
    ],
    cages: [
      { id: 'L24_C1', cells: [{ row: 0, col: 0 }, { row: 0, col: 1 }], target: 3, operation: '+' },
      { id: 'L24_C2', cells: [{ row: 0, col: 2 }, { row: 0, col: 3 }], target: 7, operation: '+' },
      { id: 'L24_C3', cells: [{ row: 0, col: 4 }, { row: 0, col: 5 }], target: 11, operation: '+' },
      { id: 'L24_C4', cells: [{ row: 1, col: 0 }, { row: 1, col: 1 }], target: 9, operation: '+' },
      { id: 'L24_C5', cells: [{ row: 1, col: 2 }, { row: 1, col: 3 }], target: 9, operation: '+' },
      { id: 'L24_C6', cells: [{ row: 1, col: 4 }, { row: 1, col: 5 }], target: 3, operation: '+' },
      { id: 'L24_C7', cells: [{ row: 2, col: 0 }, { row: 2, col: 1 }], target: 5, operation: '+' },
      { id: 'L24_C8', cells: [{ row: 2, col: 2 }, { row: 2, col: 3 }], target: 6, operation: '+' },
      { id: 'L24_C9', cells: [{ row: 2, col: 4 }, { row: 2, col: 5 }], target: 10, operation: '+' },
      { id: 'L24_C10', cells: [{ row: 3, col: 0 }, { row: 3, col: 1 }], target: 11, operation: '+' },
      { id: 'L24_C11', cells: [{ row: 3, col: 2 }, { row: 3, col: 3 }], target: 6, operation: '+' },
      { id: 'L24_C12', cells: [{ row: 3, col: 4 }, { row: 3, col: 5 }], target: 4, operation: '+' },
      { id: 'L24_C13', cells: [{ row: 4, col: 0 }, { row: 4, col: 1 }], target: 4, operation: '+' },
      { id: 'L24_C14', cells: [{ row: 4, col: 2 }, { row: 4, col: 3 }], target: 8, operation: '+' },
      { id: 'L24_C15', cells: [{ row: 4, col: 4 }, { row: 4, col: 5 }], target: 9, operation: '+' },
      { id: 'L24_C16', cells: [{ row: 5, col: 0 }, { row: 5, col: 1 }], target: 10, operation: '+' },
      { id: 'L24_C17', cells: [{ row: 5, col: 2 }, { row: 5, col: 3 }], target: 6, operation: '+' },
      { id: 'L24_C18', cells: [{ row: 5, col: 4 }, { row: 5, col: 5 }], target: 5, operation: '+' },
    ],
  },
  {
    id: 25,
    gridSize: 6,
    difficulty: 'hard',
    solution: [
      [2, 1, 4, 3, 6, 5],
      [3, 4, 5, 2, 1, 6],
      [5, 6, 1, 4, 2, 3],
      [4, 3, 2, 6, 5, 1],
      [1, 2, 6, 5, 3, 4],
      [6, 5, 3, 1, 4, 2],
    ],
    cages: [
      { id: 'L25_C1', cells: [{ row: 0, col: 0 }, { row: 1, col: 0 }, { row: 2, col: 0 }], target: 10, operation: '+' },
      { id: 'L25_C2', cells: [{ row: 0, col: 1 }, { row: 0, col: 2 }, { row: 0, col: 3 }], target: 8, operation: '+' },
      { id: 'L25_C3', cells: [{ row: 0, col: 4 }, { row: 0, col: 5 }], target: 11, operation: '+' },
      { id: 'L25_C4', cells: [{ row: 1, col: 1 }, { row: 1, col: 2 }], target: 9, operation: '+' },
      { id: 'L25_C5', cells: [{ row: 1, col: 3 }, { row: 1, col: 4 }, { row: 1, col: 5 }], target: 9, operation: '+' },
      { id: 'L25_C6', cells: [{ row: 2, col: 1 }, { row: 2, col: 2 }, { row: 3, col: 1 }], target: 13, operation: '+' },
      { id: 'L25_C7', cells: [{ row: 2, col: 3 }, { row: 2, col: 4 }, { row: 2, col: 5 }], target: 9, operation: '+' },
      { id: 'L25_C8', cells: [{ row: 3, col: 0 }, { row: 4, col: 0 }], target: 5, operation: '+' },
      { id: 'L25_C9', cells: [{ row: 3, col: 2 }, { row: 3, col: 3 }], target: 8, operation: '+' },
      { id: 'L25_C10', cells: [{ row: 3, col: 4 }, { row: 3, col: 5 }], target: 6, operation: '+' },
      { id: 'L25_C11', cells: [{ row: 4, col: 1 }, { row: 4, col: 2 }], target: 8, operation: '+' },
      { id: 'L25_C12', cells: [{ row: 4, col: 3 }, { row: 4, col: 4 }, { row: 4, col: 5 }], target: 12, operation: '+' },
      { id: 'L25_C13', cells: [{ row: 5, col: 0 }, { row: 5, col: 1 }], target: 11, operation: '+' },
      { id: 'L25_C14', cells: [{ row: 5, col: 2 }, { row: 5, col: 3 }], target: 4, operation: '+' },
      { id: 'L25_C15', cells: [{ row: 5, col: 4 }, { row: 5, col: 5 }], target: 6, operation: '+' },
    ],
  },
  {
    id: 26,
    gridSize: 6,
    difficulty: 'hard',
    solution: [
      [1, 2, 3, 4, 5, 6],
      [2, 3, 4, 5, 6, 1],
      [3, 4, 5, 6, 1, 2],
      [4, 5, 6, 1, 2, 3],
      [5, 6, 1, 2, 3, 4],
      [6, 1, 2, 3, 4, 5],
    ],
    cages: [
      { id: 'L26_C1', cells: [{ row: 0, col: 0 }, { row: 0, col: 1 }, { row: 1, col: 0 }, { row: 1, col: 1 }], target: 12, operation: '+' },
      { id: 'L26_C2', cells: [{ row: 0, col: 2 }, { row: 0, col: 3 }, { row: 0, col: 4 }], target: 12, operation: '+' },
      { id: 'L26_C3', cells: [{ row: 0, col: 5 }, { row: 1, col: 5 }], target: 7, operation: '+' },
      { id: 'L26_C4', cells: [{ row: 1, col: 2 }, { row: 1, col: 3 }, { row: 1, col: 4 }], target: 15, operation: '+' },
      { id: 'L26_C5', cells: [{ row: 2, col: 0 }, { row: 2, col: 1 }], target: 7, operation: '+' },
      { id: 'L26_C6', cells: [{ row: 2, col: 2 }, { row: 3, col: 2 }], target: 11, operation: '+' },
      { id: 'L26_C7', cells: [{ row: 2, col: 3 }, { row: 2, col: 4 }, { row: 2, col: 5 }], target: 9, operation: '+' },
      { id: 'L26_C8', cells: [{ row: 3, col: 0 }, { row: 3, col: 1 }], target: 9, operation: '+' },
      { id: 'L26_C9', cells: [{ row: 3, col: 3 }, { row: 3, col: 4 }, { row: 3, col: 5 }], target: 6, operation: '+' },
      { id: 'L26_C10', cells: [{ row: 4, col: 0 }, { row: 4, col: 1 }, { row: 5, col: 0 }], target: 17, operation: '+' },
      { id: 'L26_C11', cells: [{ row: 4, col: 2 }, { row: 4, col: 3 }], target: 3, operation: '+' },
      { id: 'L26_C12', cells: [{ row: 4, col: 4 }, { row: 4, col: 5 }], target: 7, operation: '+' },
      { id: 'L26_C13', cells: [{ row: 5, col: 1 }, { row: 5, col: 2 }, { row: 5, col: 3 }], target: 6, operation: '+' },
      { id: 'L26_C14', cells: [{ row: 5, col: 4 }, { row: 5, col: 5 }], target: 9, operation: '+' },
    ],
  },
  {
    id: 27,
    gridSize: 6,
    difficulty: 'hard',
    solution: [
      [1, 2, 3, 4, 5, 6],
      [2, 3, 4, 5, 6, 1],
      [3, 4, 5, 6, 1, 2],
      [4, 5, 6, 1, 2, 3],
      [5, 6, 1, 2, 3, 4],
      [6, 1, 2, 3, 4, 5],
    ],
    cages: [
      { id: 'L27_C1', cells: [{ row: 0, col: 0 }, { row: 0, col: 1 }, { row: 0, col: 2 }, { row: 1, col: 2 }], target: 10, operation: '+' },
      { id: 'L27_C2', cells: [{ row: 0, col: 3 }, { row: 0, col: 4 }], target: 9, operation: '+' },
      { id: 'L27_C3', cells: [{ row: 0, col: 5 }, { row: 1, col: 5 }], target: 7, operation: '+' },
      { id: 'L27_C4', cells: [{ row: 1, col: 0 }, { row: 1, col: 1 }], target: 5, operation: '+' },
      { id: 'L27_C5', cells: [{ row: 1, col: 3 }, { row: 1, col: 4 }], target: 11, operation: '+' },
      { id: 'L27_C6', cells: [{ row: 2, col: 0 }, { row: 2, col: 1 }, { row: 3, col: 0 }], target: 11, operation: '+' },
      { id: 'L27_C7', cells: [{ row: 2, col: 2 }, { row: 2, col: 3 }], target: 11, operation: '+' },
      { id: 'L27_C8', cells: [{ row: 2, col: 4 }, { row: 2, col: 5 }], target: 3, operation: '+' },
      { id: 'L27_C9', cells: [{ row: 3, col: 1 }, { row: 3, col: 2 }], target: 11, operation: '+' },
      { id: 'L27_C10', cells: [{ row: 3, col: 3 }, { row: 3, col: 4 }], target: 3, operation: '+' },
      { id: 'L27_C11', cells: [{ row: 3, col: 5 }, { row: 4, col: 5 }], target: 7, operation: '+' },
      { id: 'L27_C12', cells: [{ row: 4, col: 0 }, { row: 4, col: 1 }], target: 11, operation: '+' },
      { id: 'L27_C13', cells: [{ row: 4, col: 2 }, { row: 4, col: 3 }], target: 3, operation: '+' },
      { id: 'L27_C14', cells: [{ row: 4, col: 4 }], target: 3, operation: '+' },
      { id: 'L27_C15', cells: [{ row: 5, col: 0 }, { row: 5, col: 1 }, { row: 5, col: 2 }], target: 9, operation: '+' },
      { id: 'L27_C16', cells: [{ row: 5, col: 3 }, { row: 5, col: 4 }, { row: 5, col: 5 }], target: 12, operation: '+' },
    ],
  },
  {
    id: 28,
    gridSize: 8,
    difficulty: 'hard',
    solution: [
      [1, 2, 3, 4, 5, 6, 7, 8],
      [5, 6, 7, 8, 1, 2, 3, 4],
      [2, 3, 4, 5, 6, 7, 8, 1],
      [6, 7, 8, 1, 2, 3, 4, 5],
      [3, 4, 5, 6, 7, 8, 1, 2],
      [7, 8, 1, 2, 3, 4, 5, 6],
      [4, 5, 6, 7, 8, 1, 2, 3],
      [8, 1, 2, 3, 4, 5, 6, 7],
    ],
    cages: [
      { id: 'L28_C1', cells: [{ row: 0, col: 0 }, { row: 0, col: 1 }], target: 3, operation: '+' },
      { id: 'L28_C2', cells: [{ row: 0, col: 2 }, { row: 0, col: 3 }], target: 7, operation: '+' },
      { id: 'L28_C3', cells: [{ row: 0, col: 4 }, { row: 0, col: 5 }], target: 11, operation: '+' },
      { id: 'L28_C4', cells: [{ row: 0, col: 6 }, { row: 0, col: 7 }], target: 15, operation: '+' },
      { id: 'L28_C5', cells: [{ row: 1, col: 0 }, { row: 1, col: 1 }], target: 11, operation: '+' },
      { id: 'L28_C6', cells: [{ row: 1, col: 2 }, { row: 1, col: 3 }], target: 15, operation: '+' },
      { id: 'L28_C7', cells: [{ row: 1, col: 4 }, { row: 1, col: 5 }], target: 3, operation: '+' },
      { id: 'L28_C8', cells: [{ row: 1, col: 6 }, { row: 1, col: 7 }], target: 7, operation: '+' },
      { id: 'L28_C9', cells: [{ row: 2, col: 0 }, { row: 2, col: 1 }], target: 5, operation: '+' },
      { id: 'L28_C10', cells: [{ row: 2, col: 2 }, { row: 2, col: 3 }], target: 9, operation: '+' },
      { id: 'L28_C11', cells: [{ row: 2, col: 4 }, { row: 2, col: 5 }], target: 13, operation: '+' },
      { id: 'L28_C12', cells: [{ row: 2, col: 6 }, { row: 2, col: 7 }], target: 9, operation: '+' },
      { id: 'L28_C13', cells: [{ row: 3, col: 0 }, { row: 3, col: 1 }], target: 13, operation: '+' },
      { id: 'L28_C14', cells: [{ row: 3, col: 2 }, { row: 3, col: 3 }], target: 9, operation: '+' },
      { id: 'L28_C15', cells: [{ row: 3, col: 4 }, { row: 3, col: 5 }], target: 5, operation: '+' },
      { id: 'L28_C16', cells: [{ row: 3, col: 6 }, { row: 3, col: 7 }], target: 9, operation: '+' },
      { id: 'L28_C17', cells: [{ row: 4, col: 0 }, { row: 4, col: 1 }], target: 7, operation: '+' },
      { id: 'L28_C18', cells: [{ row: 4, col: 2 }, { row: 4, col: 3 }], target: 11, operation: '+' },
      { id: 'L28_C19', cells: [{ row: 4, col: 4 }, { row: 4, col: 5 }], target: 15, operation: '+' },
      { id: 'L28_C20', cells: [{ row: 4, col: 6 }, { row: 4, col: 7 }], target: 3, operation: '+' },
      { id: 'L28_C21', cells: [{ row: 5, col: 0 }, { row: 5, col: 1 }], target: 15, operation: '+' },
      { id: 'L28_C22', cells: [{ row: 5, col: 2 }, { row: 5, col: 3 }], target: 3, operation: '+' },
      { id: 'L28_C23', cells: [{ row: 5, col: 4 }, { row: 5, col: 5 }], target: 7, operation: '+' },
      { id: 'L28_C24', cells: [{ row: 5, col: 6 }, { row: 5, col: 7 }], target: 11, operation: '+' },
      { id: 'L28_C25', cells: [{ row: 6, col: 0 }, { row: 6, col: 1 }], target: 9, operation: '+' },
      { id: 'L28_C26', cells: [{ row: 6, col: 2 }, { row: 6, col: 3 }], target: 13, operation: '+' },
      { id: 'L28_C27', cells: [{ row: 6, col: 4 }, { row: 6, col: 5 }], target: 9, operation: '+' },
      { id: 'L28_C28', cells: [{ row: 6, col: 6 }, { row: 6, col: 7 }], target: 5, operation: '+' },
      { id: 'L28_C29', cells: [{ row: 7, col: 0 }, { row: 7, col: 1 }], target: 9, operation: '+' },
      { id: 'L28_C30', cells: [{ row: 7, col: 2 }, { row: 7, col: 3 }], target: 5, operation: '+' },
      { id: 'L28_C31', cells: [{ row: 7, col: 4 }, { row: 7, col: 5 }], target: 9, operation: '+' },
      { id: 'L28_C32', cells: [{ row: 7, col: 6 }, { row: 7, col: 7 }], target: 13, operation: '+' },
    ],
  },
  {
    id: 29,
    gridSize: 8,
    difficulty: 'hard',
    solution: [
      [8, 1, 2, 3, 4, 5, 6, 7],
      [4, 5, 6, 7, 8, 1, 2, 3],
      [2, 3, 4, 5, 6, 7, 8, 1],
      [6, 7, 8, 1, 2, 3, 4, 5],
      [1, 2, 3, 4, 5, 6, 7, 8],
      [5, 6, 7, 8, 1, 2, 3, 4],
      [3, 4, 5, 6, 7, 8, 1, 2],
      [7, 8, 1, 2, 3, 4, 5, 6],
    ],
    cages: [
      { id: 'L29_C1', cells: [{ row: 0, col: 0 }, { row: 1, col: 0 }], target: 4, operation: '-' },
      { id: 'L29_C2', cells: [{ row: 0, col: 1 }, { row: 0, col: 2 }], target: 1, operation: '-' },
      { id: 'L29_C3', cells: [{ row: 0, col: 3 }, { row: 0, col: 4 }], target: 1, operation: '-' },
      { id: 'L29_C4', cells: [{ row: 0, col: 5 }, { row: 0, col: 6 }], target: 1, operation: '-' },
      { id: 'L29_C5', cells: [{ row: 0, col: 7 }, { row: 1, col: 7 }], target: 4, operation: '-' },
      { id: 'L29_C6', cells: [{ row: 1, col: 1 }, { row: 1, col: 2 }], target: 1, operation: '-' },
      { id: 'L29_C7', cells: [{ row: 1, col: 3 }, { row: 1, col: 4 }], target: 1, operation: '-' },
      { id: 'L29_C8', cells: [{ row: 1, col: 5 }, { row: 1, col: 6 }], target: 1, operation: '-' },
      { id: 'L29_C9', cells: [{ row: 2, col: 0 }, { row: 3, col: 0 }], target: 4, operation: '-' },
      { id: 'L29_C10', cells: [{ row: 2, col: 1 }, { row: 2, col: 2 }], target: 1, operation: '-' },
      { id: 'L29_C11', cells: [{ row: 2, col: 3 }, { row: 2, col: 4 }], target: 1, operation: '-' },
      { id: 'L29_C12', cells: [{ row: 2, col: 5 }, { row: 2, col: 6 }], target: 1, operation: '-' },
      { id: 'L29_C13', cells: [{ row: 2, col: 7 }, { row: 3, col: 7 }], target: 4, operation: '-' },
      { id: 'L29_C14', cells: [{ row: 3, col: 1 }, { row: 3, col: 2 }], target: 1, operation: '-' },
      { id: 'L29_C15', cells: [{ row: 3, col: 3 }, { row: 3, col: 4 }], target: 1, operation: '-' },
      { id: 'L29_C16', cells: [{ row: 3, col: 5 }, { row: 3, col: 6 }], target: 1, operation: '-' },
      { id: 'L29_C17', cells: [{ row: 4, col: 0 }, { row: 5, col: 0 }], target: 4, operation: '-' },
      { id: 'L29_C18', cells: [{ row: 4, col: 1 }, { row: 4, col: 2 }], target: 1, operation: '-' },
      { id: 'L29_C19', cells: [{ row: 4, col: 3 }, { row: 4, col: 4 }], target: 1, operation: '-' },
      { id: 'L29_C20', cells: [{ row: 4, col: 5 }, { row: 4, col: 6 }], target: 1, operation: '-' },
      { id: 'L29_C21', cells: [{ row: 4, col: 7 }, { row: 5, col: 7 }], target: 4, operation: '-' },
      { id: 'L29_C22', cells: [{ row: 5, col: 1 }, { row: 5, col: 2 }], target: 1, operation: '-' },
      { id: 'L29_C23', cells: [{ row: 5, col: 3 }, { row: 5, col: 4 }], target: 1, operation: '-' },
      { id: 'L29_C24', cells: [{ row: 5, col: 5 }, { row: 5, col: 6 }], target: 1, operation: '-' },
      { id: 'L29_C25', cells: [{ row: 6, col: 0 }, { row: 7, col: 0 }], target: 4, operation: '-' },
      { id: 'L29_C26', cells: [{ row: 6, col: 1 }, { row: 6, col: 2 }], target: 1, operation: '-' },
      { id: 'L29_C27', cells: [{ row: 6, col: 3 }, { row: 6, col: 4 }], target: 1, operation: '-' },
      { id: 'L29_C28', cells: [{ row: 6, col: 5 }, { row: 6, col: 6 }], target: 1, operation: '-' },
      { id: 'L29_C29', cells: [{ row: 6, col: 7 }, { row: 7, col: 7 }], target: 4, operation: '-' },
      { id: 'L29_C30', cells: [{ row: 7, col: 1 }, { row: 7, col: 2 }], target: 1, operation: '-' },
      { id: 'L29_C31', cells: [{ row: 7, col: 3 }, { row: 7, col: 4 }], target: 1, operation: '-' },
      { id: 'L29_C32', cells: [{ row: 7, col: 5 }, { row: 7, col: 6 }], target: 1, operation: '-' },
    ],
  },
  {
    id: 30,
    gridSize: 9,
    difficulty: 'expert',
    solution: [
      [1, 2, 3, 4, 5, 6, 7, 8, 9],
      [4, 5, 6, 7, 8, 9, 1, 2, 3],
      [7, 8, 9, 1, 2, 3, 4, 5, 6],
      [2, 3, 4, 5, 6, 7, 8, 9, 1],
      [5, 6, 7, 8, 9, 1, 2, 3, 4],
      [8, 9, 1, 2, 3, 4, 5, 6, 7],
      [3, 4, 5, 6, 7, 8, 9, 1, 2],
      [6, 7, 8, 9, 1, 2, 3, 4, 5],
      [9, 1, 2, 3, 4, 5, 6, 7, 8],
    ],
    cages: [
      { id: 'L30_C1', cells: [{ row: 0, col: 0 }, { row: 0, col: 1 }, { row: 0, col: 2 }], target: 6, operation: '+' },
      { id: 'L30_C2', cells: [{ row: 0, col: 3 }, { row: 0, col: 4 }, { row: 0, col: 5 }], target: 15, operation: '+' },
      { id: 'L30_C3', cells: [{ row: 0, col: 6 }, { row: 0, col: 7 }, { row: 0, col: 8 }], target: 24, operation: '+' },
      { id: 'L30_C4', cells: [{ row: 1, col: 0 }, { row: 1, col: 1 }, { row: 1, col: 2 }], target: 15, operation: '+' },
      { id: 'L30_C5', cells: [{ row: 1, col: 3 }, { row: 1, col: 4 }, { row: 1, col: 5 }], target: 24, operation: '+' },
      { id: 'L30_C6', cells: [{ row: 1, col: 6 }, { row: 1, col: 7 }, { row: 1, col: 8 }], target: 6, operation: '+' },
      { id: 'L30_C7', cells: [{ row: 2, col: 0 }, { row: 2, col: 1 }, { row: 2, col: 2 }], target: 24, operation: '+' },
      { id: 'L30_C8', cells: [{ row: 2, col: 3 }, { row: 2, col: 4 }, { row: 2, col: 5 }], target: 6, operation: '+' },
      { id: 'L30_C9', cells: [{ row: 2, col: 6 }, { row: 2, col: 7 }, { row: 2, col: 8 }], target: 15, operation: '+' },
      { id: 'L30_C10', cells: [{ row: 3, col: 0 }, { row: 3, col: 1 }, { row: 3, col: 2 }], target: 9, operation: '+' },
      { id: 'L30_C11', cells: [{ row: 3, col: 3 }, { row: 3, col: 4 }, { row: 3, col: 5 }], target: 18, operation: '+' },
      { id: 'L30_C12', cells: [{ row: 3, col: 6 }, { row: 3, col: 7 }, { row: 3, col: 8 }], target: 18, operation: '+' },
      { id: 'L30_C13', cells: [{ row: 4, col: 0 }, { row: 4, col: 1 }, { row: 4, col: 2 }], target: 18, operation: '+' },
      { id: 'L30_C14', cells: [{ row: 4, col: 3 }, { row: 4, col: 4 }, { row: 4, col: 5 }], target: 18, operation: '+' },
      { id: 'L30_C15', cells: [{ row: 4, col: 6 }, { row: 4, col: 7 }, { row: 4, col: 8 }], target: 9, operation: '+' },
      { id: 'L30_C16', cells: [{ row: 5, col: 0 }, { row: 5, col: 1 }, { row: 5, col: 2 }], target: 18, operation: '+' },
      { id: 'L30_C17', cells: [{ row: 5, col: 3 }, { row: 5, col: 4 }, { row: 5, col: 5 }], target: 9, operation: '+' },
      { id: 'L30_C18', cells: [{ row: 5, col: 6 }, { row: 5, col: 7 }, { row: 5, col: 8 }], target: 18, operation: '+' },
      { id: 'L30_C19', cells: [{ row: 6, col: 0 }, { row: 6, col: 1 }, { row: 6, col: 2 }], target: 12, operation: '+' },
      { id: 'L30_C20', cells: [{ row: 6, col: 3 }, { row: 6, col: 4 }, { row: 6, col: 5 }], target: 21, operation: '+' },
      { id: 'L30_C21', cells: [{ row: 6, col: 6 }, { row: 6, col: 7 }, { row: 6, col: 8 }], target: 12, operation: '+' },
      { id: 'L30_C22', cells: [{ row: 7, col: 0 }, { row: 7, col: 1 }, { row: 7, col: 2 }], target: 21, operation: '+' },
      { id: 'L30_C23', cells: [{ row: 7, col: 3 }, { row: 7, col: 4 }, { row: 7, col: 5 }], target: 12, operation: '+' },
      { id: 'L30_C24', cells: [{ row: 7, col: 6 }, { row: 7, col: 7 }, { row: 7, col: 8 }], target: 12, operation: '+' },
      { id: 'L30_C25', cells: [{ row: 8, col: 0 }, { row: 8, col: 1 }, { row: 8, col: 2 }], target: 12, operation: '+' },
      { id: 'L30_C26', cells: [{ row: 8, col: 3 }, { row: 8, col: 4 }, { row: 8, col: 5 }], target: 12, operation: '+' },
      { id: 'L30_C27', cells: [{ row: 8, col: 6 }, { row: 8, col: 7 }, { row: 8, col: 8 }], target: 21, operation: '+' },
    ],
  },
];

export const getLevelById = (id: number): KenKenLevel | undefined => {
  return KENKEN_LEVELS.find((level) => level.id === id);
};

export const getTotalLevels = (): number => {
  return KENKEN_LEVELS.length;
};
