export const MathMazeColors = {
  SCREEN_BG: '#0D0D0D',
  HEADER_BG: '#0D0D0D',

  PLAYER_AVATAR_BG: '#7B7FC4',
  PLAYER_NAME_COLOR: '#FFFFFF',
  PLAYER_SCORE_COLOR: '#AAAAAA',

  SCORE_BADGE_BG: '#1E1E1E',
  SCORE_BADGE_TEXT: '#FFFFFF',

  TIMER_BG: '#00BCD4',
  TIMER_TEXT: '#FFFFFF',
  TIMER_ICON: '#FFFFFF',

  TARGET_LABEL: 'rgba(255,255,255,0.35)',
  TARGET_ICON: '#888888',
  TARGET_VALUE: '#8B8FE8',
  TARGET_WRONG_COLOR: '#FF3B3B',

  CELL_DEFAULT_BG: '#2A2A3D',
  CELL_DEFAULT_TEXT: '#8B8FE8',
  CELL_SELECTED_BG: '#EDE89A',
  CELL_SELECTED_TEXT: '#1A1A1A',
  CELL_START_BG: '#EDE89A',
  CELL_END_BG: '#EDE89A',
  CELL_WRONG_BG: '#FF3B3B',
  CELL_WRONG_TEXT: '#FFFFFF',

  PATH_LINE_COLOR: '#EDE89A',
  PATH_LINE_WRONG: '#FF3B3B',

  START_LABEL_BG: '#1A1A1A',
  START_LABEL_BORDER: '#EDE89A',
  START_LABEL_TEXT: '#FFFFFF',
  END_LABEL_BG: '#1A1A1A',
  END_LABEL_BORDER: '#EDE89A',
  END_LABEL_TEXT: '#FFFFFF',

  ACTION_BUTTON_BG: '#1E1E1E',
  ACTION_BUTTON_TEXT: '#FFFFFF',
} as const
